name: Validate manifests and tests

on:
  push:
    branches: [ main, 'copilot/**', '**' ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install
        run: npm ci
      - name: Validate manifests
        run: npm run validate:manifests
      - name: Run tests
        run: npm test
